name: Setup R for TinyTeX build
description: Common setup steps shared across TinyTeX build jobs

runs:
  using: composite
  steps:
    - name: Clean up any existing TinyTeX bundles
      run: rm -f TinyTeX-*.* TinyTeX.*
      shell: bash

    - name: Install Pandoc
      uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: '2.19.2'

    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Install tinytex package and its deps
      uses: yihui/actions/setup-r-dependencies@HEAD
      with:
        extra-packages: . rmarkdown

    - name: Update all packages
      run: |
        try(update.packages(ask = FALSE, checkBuilt = TRUE))
      shell: Rscript {0}
