
name: Check Chocolatey Package
on:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get and Upload Packages
      run: |
        cd tools\choco\tinytex
        choco pack
        choco install --no-progress tinytex -source "'.;https://chocolatey.org/api/v2/'"
        choco uninstall -y tinytex
        cd ..\..\
    - name: Upload Logs if failes
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: chocologs
        path: C:\ProgramData\chocolatey\logs\chocolatey.log
    - name: Upload Logs if Sucess
      uses: actions/upload-artifact@v2
      with:
        name: chocologs
        path: C:\ProgramData\chocolatey\logs\chocolatey.log