name: Get Latest Version And Publish

on:
  push:
    branches:
    - main
    - choco

jobs:
  check:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test TinyTex Choco Package
      run: |
        cd "tools\choco\tinytex"
        choco pack
        choco install tinytex -source "'.;https://chocolatey.org/api/v2/'"  

    - name: Upload Logs if failes
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: chocologs
        path: C:\ProgramData\chocolatey\logs\chocolatey.log
    - name: Upload Logs if Sucess
      uses: actions/upload-artifact@v2
      with:
        name: chocologs
        path: C:\ProgramData\chocolatey\logs\chocolatey.log
