# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches: main
  pull_request:
    branches: main

name: check required LateX packages

jobs:
  LateX-Packages:
    runs-on: ubuntu-18.04

    name: Ubuntu 18-04 (release)

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-tinytex@v1
        env:
          # install prebuilt base version (infraonly)
          TINYTEX_INSTALLER: TinyTeX-0

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            curl,
            yihui/knitr

      - name: Find required LateX packages
        run: Rscript tools/test-packages.R
