on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/workflows/build.yaml'
  pull_request:
    branches: [main]
    paths-ignore:
      - '.github/workflows/build.yaml'

name: check required LateX packages

jobs:
  LateX-Packages:
    runs-on: ubuntu-latest

    name: Ubuntu (release)

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2
        env:
          # install prebuilt base version (infraonly)
          TINYTEX_INSTALLER: TinyTeX-0

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::curl, any::kableExtra, any::bookdown

      - name: Find required LaTeX packages
        run: Rscript tools/test-packages.R

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: Update the list of LaTeX packages
          body: New results by running `tools/test-packages.R`.
          commit-message: Update the list of LaTeX packages
          add-paths: |
            R/platforms.R
            tools/pkgs-custom.txt
            tools/pkgs-yihui.txt
